type Usuario {
  id: Int
  nome: String
  email: String
  telefone: String
  perfil: Perfil
}

input UsuarioInput {
  nome: String
  email: String
  telefone: String
}

type Query {
  usuario(id: Int): Usuario
  usuarios: [Usuario]
}

type Mutation {
  criarUsuario(data: UsuarioInput): Usuario!
  atualizarUsuario(id: Int!, data: UsuarioInput): Usuario!
}
